/* ============================================================
   ScoreQuest — the capybara companion
   ------------------------------------------------------------
   Quantized from Magnolia's chosen sprite art (side view) into a
   true 38x33 pixel grid, with programmatic waddle + blink frames.
   Frames: 0 idle, 1/2 walk, 3 blink. Faces right; flip via CSS.
   ============================================================ */
(function () {
  'use strict';
  var COLORS = {"a": "#7f3e22", "b": "#9e643f", "e": "#f58119", "m": "#82c82b", "n": "#f8ad31", "o": "#bf7e51", "s": "#18100b"};
  var FRAMES = [
    ["...........................sss........", "..........................smms........", "........................ssess.........", "........................sneees........", ".......................sbeeees........", "...................sssosaeeees........", "..................sbbassaaeeasss......", "..................saoosoobaabooosss...", "..................saooboooooooooobs...", ".................sssaooooooooooooobs..", "........sssssss.sbooooooooooooooooobs.", ".....ssaooooooosaaooooooooooooooobbbbs", "....soooooooooooooooooooosssoooobbbbbs", "...sooooooooooooooooooooooaaoooobaaabs", "..sooooooooooooooooooooooooooooobbbbbs", "..oaoooooooooooooooooooooooooooobbbbbs", ".sbooooooooooooooooooooooooooooobbbbbs", ".soooooooooooooooooooooooooooooobbbbbs", "soooooooooooooooooooooooooooooooobbbab", "soooooooooooooooooooooobooooooooobba..", "sbboooooooooooooooooooobbooobbbbbsss..", ".sobooboooooooooooooooooobbaaasss.....", ".sboooobooooooooooooooooobbbbbs.......", "sobbooboooobobooooooooobbbbba.........", ".sbbbbbobbbbbbobooooobobbbbbs.........", ".sabbbbbbbbbbbbbboooobbbbbbs..........", "..sbbbbbbabaababaooooabbbbbs..........", "..sbbbbbbaaaaaasboooabbaaas...........", "...sbbbbasssssssbooossaaaas...........", "...sbabassoos...sboosasaaas...........", "....saaaassbs...sbbbsassaass..........", "....ssaasssss....saaasasssss..........", ".....ssss........sssss................"],
    ["...........................sss........", "..........................smms........", "........................ssess.........", "........................sneees........", ".......................sbeeees........", "...................sssosaeeees........", "..................sbbassaaeeasss......", "..................saoosoobaabooosss...", "..................saooboooooooooobs...", ".................sssaooooooooooooobs..", "........sssssss.sbooooooooooooooooobs.", ".....ssaooooooosaaooooooooooooooobbbbs", "....soooooooooooooooooooosssoooobbbbbs", "...sooooooooooooooooooooooaaoooobaaabs", "..sooooooooooooooooooooooooooooobbbbbs", "..oaoooooooooooooooooooooooooooobbbbbs", ".sbooooooooooooooooooooooooooooobbbbbs", ".soooooooooooooooooooooooooooooobbbbbs", "soooooooooooooooooooooooooooooooobbbab", "soooooooooooooooooooooobooooooooobba..", "sbboooooooooooooooooooobbooobbbbbsss..", ".sobooboooooooooooooooooobbaaasss.....", ".sboooobooooooooooooooooobbbbbs.......", "sobbooboooobobooooooooobbbbba.........", ".sbbbbbobbbbbbobooooobobbbbbs.........", ".sabbbbbbbbbbbbbboooobbbbbbs..........", "..sbbbbbbabaababaooooabbbbbs..........", "..sbbbbbbaaaaaasboooabbaaas...........", "...sbbbbasssssssbooossaaaas...........", "..sbabassoos.....sboosasaaas..........", "...saaaassbs.....sbbbsassaass.........", "...ssaasssss......saaasasssss.........", "....ssss..........sssss..............."],
    ["...........................sss........", "..........................smms........", "........................ssess.........", "........................sneees........", ".......................sbeeees........", "...................sssosaeeees........", "..................sbbassaaeeasss......", "..................saoosoobaabooosss...", "..................saooboooooooooobs...", ".................sssaooooooooooooobs..", "........sssssss.sbooooooooooooooooobs.", ".....ssaooooooosaaooooooooooooooobbbbs", "....soooooooooooooooooooosssoooobbbbbs", "...sooooooooooooooooooooooaaoooobaaabs", "..sooooooooooooooooooooooooooooobbbbbs", "..oaoooooooooooooooooooooooooooobbbbbs", ".sbooooooooooooooooooooooooooooobbbbbs", ".soooooooooooooooooooooooooooooobbbbbs", "soooooooooooooooooooooooooooooooobbbab", "soooooooooooooooooooooobooooooooobba..", "sbboooooooooooooooooooobbooobbbbbsss..", ".sobooboooooooooooooooooobbaaasss.....", ".sboooobooooooooooooooooobbbbbs.......", "sobbooboooobobooooooooobbbbba.........", ".sbbbbbobbbbbbobooooobobbbbbs.........", ".sabbbbbbbbbbbbbboooobbbbbbs..........", "..sbbbbbbabaababaooooabbbbbs..........", "..sbbbbbbaaaaaasboooabbaaas...........", "...sbbbbasssssssbooossaaaas...........", "....sbabassoos.sboosasaaas............", ".....saaaassbs.sbbbsassaass...........", ".....ssaasssss..saaasasssss...........", "......ssss......sssss................."],
    ["...........................sss........", "..........................smms........", "........................ssess.........", "........................sneees........", ".......................sbeeees........", "...................sssosaeeees........", "..................sbbassaaeeasss......", "..................saoosoobaabooosss...", "..................saooboooooooooobs...", ".................sssaooooooooooooobs..", "........sssssss.sbooooooooooooooooobs.", ".....ssaooooooosaaooooooooooooooobbbbs", "....sooooooooooooooooooooooooooobbbbbs", "...sooooooooooooooooooooooaaoooobaaabs", "..sooooooooooooooooooooooooooooobbbbbs", "..oaoooooooooooooooooooooooooooobbbbbs", ".sbooooooooooooooooooooooooooooobbbbbs", ".soooooooooooooooooooooooooooooobbbbbs", "soooooooooooooooooooooooooooooooobbbab", "soooooooooooooooooooooobooooooooobba..", "sbboooooooooooooooooooobbooobbbbbsss..", ".sobooboooooooooooooooooobbaaasss.....", ".sboooobooooooooooooooooobbbbbs.......", "sobbooboooobobooooooooobbbbba.........", ".sbbbbbobbbbbbobooooobobbbbbs.........", ".sabbbbbbbbbbbbbboooobbbbbbs..........", "..sbbbbbbabaababaooooabbbbbs..........", "..sbbbbbbaaaaaasboooabbaaas...........", "...sbbbbasssssssbooossaaaas...........", "...sbabassoos...sboosasaaas...........", "....saaaassbs...sbbbsassaass..........", "....ssaasssss....saaasasssss..........", ".....ssss........sssss................"]
  ];
  function draw(ctx, frame) {
    var map = FRAMES[frame] || FRAMES[0];
    ctx.clearRect(0, 0, 38, 33);
    for (var y = 0; y < map.length; y++) {
      var row = map[y];
      for (var x = 0; x < row.length; x++) {
        var ch = row[x];
        if (ch === '.') continue;
        ctx.fillStyle = COLORS[ch];
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  window.SQCompanion = { w: 38, h: 33, draw: draw };
})();
