/* ============================================================
   ScoreQuest — the capybara companion
   ------------------------------------------------------------
   Quantized from Magnolia's sprite art. The idle graze sequence:
   stand -> sit -> half-bend -> graze at the ground -> half-bend ->
   chew. Frames: 0 stand, 1/2 walk, 3 blink, 4 sit upright,
   5 half-bend tween, 6 graze (head at the ground), 7/8 chew.
   Canvas 42x39, bottom-aligned, faces right.
   ============================================================ */
(function () {
  'use strict';
  var COLORS = {"o": "#bf7e51", "b": "#9e643f", "s": "#18100b", "m": "#82c82b", "e": "#f58119", "n": "#f8ad31", "a": "#7f3e22"};
  var FRAMES = [
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", ".............................sss..........", "............................smms..........", "..........................ssess...........", "..........................sneees..........", ".........................sbeeees..........", ".....................sssosaeeees..........", "....................sbbassaaeeasss........", "....................saoosoobaabooosss.....", "....................saooboooooooooobs.....", "...................sssaooooooooooooobs....", "..........sssssss.sbooooooooooooooooobs...", ".......ssaooooooosaaooooooooooooooobbbbs..", "......soooooooooooooooooooosssoooobbbbbs..", ".....sooooooooooooooooooooooaaoooobaaabs..", "....sooooooooooooooooooooooooooooobbbbbs..", "....oaoooooooooooooooooooooooooooobbbbbs..", "...sbooooooooooooooooooooooooooooobbbbbs..", "...soooooooooooooooooooooooooooooobbbbbs..", "..soooooooooooooooooooooooooooooooobbbab..", "..soooooooooooooooooooooobooooooooobba....", "..sbboooooooooooooooooooobbooobbbbbsss....", "...sobooboooooooooooooooooobbaaasss.......", "...sboooobooooooooooooooooobbbbbs.........", "..sobbooboooobobooooooooobbbbba...........", "...sbbbbbobbbbbbobooooobobbbbbs...........", "...sabbbbbbbbbbbbbboooobbbbbbs............", "....sbbbbbbabaababaooooabbbbbs............", "....sbbbbbbaaaaaasboooabbaaas.............", ".....sbbbbasssssssbooossaaaas.............", ".....sbabassoos...sboosasaaas.............", "......saaaassbs...sbbbsassaass............", "......ssaasssss....saaasasssss............", ".......ssss........sssss.................."],
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", ".............................sss..........", "............................smms..........", "..........................ssess...........", "..........................sneees..........", ".........................sbeeees..........", ".....................sssosaeeees..........", "....................sbbassaaeeasss........", "....................saoosoobaabooosss.....", "....................saooboooooooooobs.....", "...................sssaooooooooooooobs....", "..........sssssss.sbooooooooooooooooobs...", ".......ssaooooooosaaooooooooooooooobbbbs..", "......soooooooooooooooooooosssoooobbbbbs..", ".....sooooooooooooooooooooooaaoooobaaabs..", "....sooooooooooooooooooooooooooooobbbbbs..", "....oaoooooooooooooooooooooooooooobbbbbs..", "...sbooooooooooooooooooooooooooooobbbbbs..", "...soooooooooooooooooooooooooooooobbbbbs..", "..soooooooooooooooooooooooooooooooobbbab..", "..soooooooooooooooooooooobooooooooobba....", "..sbboooooooooooooooooooobbooobbbbbsss....", "...sobooboooooooooooooooooobbaaasss.......", "...sboooobooooooooooooooooobbbbbs.........", "..sobbooboooobobooooooooobbbbba...........", "...sbbbbbobbbbbbobooooobobbbbbs...........", "...sabbbbbbbbbbbbbboooobbbbbbs............", "....sbbbbbbabaababaooooabbbbbs............", "....sbbbbbbaaaaaasboooabbaaas.............", ".....sbbbbasssssssbooossaaaas.............", "....sbabassoos.....sboosasaaas............", ".....saaaassbs.....sbbbsassaass...........", ".....ssaasssss......saaasasssss...........", "......ssss..........sssss................."],
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", ".............................sss..........", "............................smms..........", "..........................ssess...........", "..........................sneees..........", ".........................sbeeees..........", ".....................sssosaeeees..........", "....................sbbassaaeeasss........", "....................saoosoobaabooosss.....", "....................saooboooooooooobs.....", "...................sssaooooooooooooobs....", "..........sssssss.sbooooooooooooooooobs...", ".......ssaooooooosaaooooooooooooooobbbbs..", "......soooooooooooooooooooosssoooobbbbbs..", ".....sooooooooooooooooooooooaaoooobaaabs..", "....sooooooooooooooooooooooooooooobbbbbs..", "....oaoooooooooooooooooooooooooooobbbbbs..", "...sbooooooooooooooooooooooooooooobbbbbs..", "...soooooooooooooooooooooooooooooobbbbbs..", "..soooooooooooooooooooooooooooooooobbbab..", "..soooooooooooooooooooooobooooooooobba....", "..sbboooooooooooooooooooobbooobbbbbsss....", "...sobooboooooooooooooooooobbaaasss.......", "...sboooobooooooooooooooooobbbbbs.........", "..sobbooboooobobooooooooobbbbba...........", "...sbbbbbobbbbbbobooooobobbbbbs...........", "...sabbbbbbbbbbbbbboooobbbbbbs............", "....sbbbbbbabaababaooooabbbbbs............", "....sbbbbbbaaaaaasboooabbaaas.............", ".....sbbbbasssssssbooossaaaas.............", "......sbabassoos.sboosasaaas..............", ".......saaaassbs.sbbbsassaass.............", ".......ssaasssss..saaasasssss.............", "........ssss......sssss..................."],
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", ".............................sss..........", "............................smms..........", "..........................ssess...........", "..........................sneees..........", ".........................sbeeees..........", ".....................sssosaeeees..........", "....................sbbassaaeeasss........", "....................saoosoobaabooosss.....", "....................saooboooooooooobs.....", "...................sssaooooooooooooobs....", "..........sssssss.sbooooooooooooooooobs...", ".......ssaooooooosaaooooooooooooooobbbbs..", "......sooooooooooooooooooooooooooobbbbbs..", ".....sooooooooooooooooooooooaaoooobaaabs..", "....sooooooooooooooooooooooooooooobbbbbs..", "....oaoooooooooooooooooooooooooooobbbbbs..", "...sbooooooooooooooooooooooooooooobbbbbs..", "...soooooooooooooooooooooooooooooobbbbbs..", "..soooooooooooooooooooooooooooooooobbbab..", "..soooooooooooooooooooooobooooooooobba....", "..sbboooooooooooooooooooobbooobbbbbsss....", "...sobooboooooooooooooooooobbaaasss.......", "...sboooobooooooooooooooooobbbbbs.........", "..sobbooboooobobooooooooobbbbba...........", "...sbbbbbobbbbbbobooooobobbbbbs...........", "...sabbbbbbbbbbbbbboooobbbbbbs............", "....sbbbbbbabaababaooooabbbbbs............", "....sbbbbbbaaaaaasboooabbaaas.............", ".....sbbbbasssssssbooossaaaas.............", ".....sbabassoos...sboosasaaas.............", "......saaaassbs...sbbbsassaass............", "......ssaasssss....saaasasssss............", ".......ssss........sssss.................."],
    ["..........................ssss............", ".........................smmms............", "........................sesss.............", ".......................snneees............", ".......................seeeees............", "...................ssssseeeees............", "..................sabsssaeeeasss..........", "..................saoosobaaabooosss.......", "..................saooboooooooooobs.......", "..................ssaooooooooooooobbs.....", ".................saooooooooooooooooobs....", ".................sooooooooooooooobbbbas...", "...............ssbooooooosssoooobbbbbas...", "...............bboooooooooaaoooobbaabas...", "............ssbboooooooooobbooooaaaaaas...", "............oooooooooooooooooooobbbbbas...", "..........aaooooooooooooooooooooabbbbbs...", "........abooooooooooooooooooooooabbbbbs...", ".......soooooooooooooooooooooooobbbbbas...", "......sooooooooooooooooooooooooooaaaas....", ".....soooooooooooooooooooooooooooaaaa.....", ".....soooooooooooooooooooooobbbbbsss......", "....soooooooooooooooooooobbbaaass.........", "...sooooooooooooooooooooooobbbsa..........", "...sooooooooooooooooooooooobbbbs..........", "..sboooooooooooooooooooooooobbbs..........", "..sbooooooooobbooooooooooooobbbs..........", "..sbboooooooooabboooooooooobbbbs..........", "..sbbooooooooooooaooooooooobabas..........", "..sbbboooooooooooobobboooobbbbs...........", "..sbbbbooooooooooobabbbooobabas...........", "..sbbbboooooooooooosbaoooosbbs............", "..sabbbbbooooooooobsaaoooosbbs............", "...saabbbbbbobooobbsasoooosbbs............", "...saaabbbbbbobbbbbsasbbobsaas............", "....saaabbbbbbbbbassaasbbbsaass...........", ".....ssabaabbbaaaaaasssaaaasaas...........", ".......sssssbababaaas..saaassss...........", "............sssssssss...ssss.............."],
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "...........................ssss...........", "..........................s...s...........", ".........................sesss............", "........................snneees...........", "................s......sseeeees...........", "...............ss...ssssseeeeess..........", "..............sss..sabsssaeeeasss.........", ".............sbbs..saoosobaaabooosss......", "...........ssbbos..saooboooooooooobss.....", "..........sooooos..ssaooooooooooooobbs....", ".........saoooooossaooooooooooooooooobs...", ".......ssooooooooooooooooooooooooobbbbas..", "......sooooooooooooooooooosssoooobbbbbas..", ".....soooooooooooooooooooooaaoooobbaabas..", "....soooooooooooooooooooooobbooooaaaaaas..", "....soooooooooooooooooooooooooooobbbbbas..", "...soooooooooooooooooooooooooooooabbbbbs..", "..sooooooooooooooooooooooooooooossssssss..", "..sooooooooooooooooooooooobbbbss..........", ".sboooooooooooooooooooooooobbbs...........", ".sbooooooooobbooooooooooooobbbs...........", ".sbboooooooooabboooooooooobbbbs...........", ".sbbooooooooooooaooooooooobabas...........", ".sbbboooooooooooobobboooobbbbs............", ".sbbbbooooooooooobabbbooobabas............", ".sbbbboooooooooooosbaoooosbbs.............", ".sabbbbbooooooooobsaaoooosbbs.............", "..saabbbbbbobooobbsasoooosbbs.............", "..saaabbbbbbobbbbbsasbbobsaas.............", "...saaabbbbbbbbbassaasbbbsaass............", "....ssabaabbbaaaaaasssaaaasaas............", "......sssssbababaaassssaaassss............", "...........sssssssss...ssss..............."],
    ["..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........................................", "..........sssssssso.......................", "........ssooooooooass.....................", "......ssoooooooooooooss..ss...............", ".....sooooooooooooooooossaas....sssss.....", "....sooooooooooooooooooosaaas..semmss.....", "...soooooooooooooooooooosaoassseesss......", "..sooooooooooooooooooooosaooaasenees......", "..sooooooooooooooooooooosaooaoseeees......", ".sooooooooooooooooooooooosaobooaeeess.....", ".sooooooooooooooooooooooooooooooaaabas....", "sbooooooooooooooooooooooooooooooooooobs...", "sbbooooooooooooooooooooooooooooooooooos...", "sbbooooooooooooooooooooooooooooooooooobs..", "sbboooooooooooooooooooooooooooooooooooobs.", "sbbbooooooooboooooooooooooooosooooooooobs.", "sabbooooooooobbooooooooooooooosaoooooobos.", "sabbboooooooooaboooooooooooooooooooooaaaas", "saabboooooooooaboboooboboooooooooooobaaaas", ".sabbbbooooooooabbooobbbaoooooooooobaaabas", ".saabbbbooooooosbboooabbaboooooooooaaaaaas", "..saabbbbboooobsbaooosaassboooooooobaaaass", "...saaabbbboobasaaboosaaasabbooooobbbaaas.", "....saaaaabbaassaabboasaaassabboooaaaaass.", ".....sssaaaaaaaassaaaaasaasassabboaaamas..", ".......ssaaaaaaassssaaassss...sssamamssa..", ".........ssssssss..sssss........mmmsmsmmm."],
    ["..........................................", "..........................ssss............", ".........................smmss............", "........................sesss.............", ".......................snneees............", "...................ssssseeeees............", "..................saasssaeeeasss..........", "..................saoosobaaaboooss........", "..................saooboooooooooobs.......", "..................ssaooooooooooooobs......", ".................saoooooooooooooooobs.....", ".................sboooooooooooooobbbas....", ".................soooooooooooooooabbbs....", "................sbooooooosssoooobbabas....", "...............sboooooooooaaooooaaaaas....", ".............ssboooooooooooooooobbbbbs....", "...........ssoooooooooooooooooooabbbbs....", ".........ssooooooooooooooooooooobbbbbs....", "........soooooooooooooooooooooooabbbbs....", ".......soooooooooooooooooooooooobbaabs....", "......soooooooooooooooobbooooooooaaaa.....", "......sooooooooooooooooobboobbbbbsssmm....", ".....sooooooooooooooooooobbbaaass....mm...", ".....sooooooooooooooooooooobbbsb..........", "....soooooooooooooooooooooobbbbs..........", "....soooooooooooooooooooooobbbbs..........", "...sbooooooooobboooooooooooobbbs..........", "...sboooooooooobooooooooooobbbbs..........", "...sbbooooooooooobooobooooobbbas..........", "...sbbbooooooooooobobboooobbabs...........", "...sbbbooooooooooobabbbooobaaas...........", "...sabbboooooooooooabaoooosabs............", "...saabbbboooooooobsaaoooosabs............", "....saabbbbbbbooobbsasoooosabs............", "....saaabbbbbbbobbbsasbbobsaas............", ".....saaabbbbbbbbasssasbbbsaass...........", "......ssaaaaaaaabaaasssaaaasaas...........", "........sssssaaaaaaas..ssaassss...........", ".............ssssssss...ssss.............."],
    ["..........................................", "..........................ssss............", ".........................smmss............", "........................sesss.............", ".......................snneees............", "...................ssssseeeees............", "..................saasssaeeeasss..........", "..................saoosobaaaboooss........", "..................saooboooooooooobs.......", "..................ssaooooooooooooobs......", ".................saoooooooooooooooobs.....", ".................sboooooooooooooobbbas....", ".................soooooooooooooooabbbs....", "................sbooooooosssoooobbabas....", "...............sboooooooooaaooooaaaaas....", ".............ssboooooooooooooooobbbbbs....", "...........ssoooooooooooooooooooabbbbs....", ".........ssooooooooooooooooooooobbbbbs....", "........soooooooooooooooooooooooabbbbs....", ".......soooooooooooooooooooooooobbaabs....", "......soooooooooooooooobbooooooooaaaa.....", "......sooooooooooooooooobboobbbbbsss......", ".....sooooooooooooooooooobbbaaass..mm.....", ".....sooooooooooooooooooooobbbsb....mm....", "....soooooooooooooooooooooobbbbs..........", "....soooooooooooooooooooooobbbbs..........", "...sbooooooooobboooooooooooobbbs..........", "...sboooooooooobooooooooooobbbbs..........", "...sbbooooooooooobooobooooobbbas..........", "...sbbbooooooooooobobboooobbabs...........", "...sbbbooooooooooobabbbooobaaas...........", "...sabbboooooooooooabaoooosabs............", "...saabbbboooooooobsaaoooosabs............", "....saabbbbbbbooobbsasoooosabs............", "....saaabbbbbbbobbbsasbbobsaas............", ".....saaabbbbbbbbasssasbbbsaass...........", "......ssaaaaaaaabaaasssaaaasaas...........", "........sssssaaaaaaas..ssaassss...........", ".............ssssssss...ssss.............."]
  ];
  function draw(ctx, frame) {
    var map = FRAMES[frame] || FRAMES[0];
    ctx.clearRect(0, 0, 42, 39);
    for (var y = 0; y < map.length; y++) {
      var row = map[y];
      for (var x = 0; x < row.length; x++) {
        var ch = row[x];
        if (ch === '.') continue;
        ctx.fillStyle = COLORS[ch];
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  window.SQCompanion = { w: 42, h: 39, draw: draw };
})();
