/* ============================================================
   ScoreQuest — Mango (fine quantization, ~42px)
   Frames: 0 sit, 1 turning, 2 back, 3/4/5 ear-scratch. 44x44.
   ============================================================ */
(function () {
  'use strict';
  var COLORS = {"a": "#c7947a", "b": "#aa7b68", "e": "#67463b", "m": "#865c4d", "n": "#666968", "o": "#deac92", "s": "#0c0600"};
  var FRAMES = [
    ["............................................", "............................................", "...........................sssss............", "....................ssss..smbbbes...........", "...................smmeesbsmmbbmsn..........", "...................smbmessbaoooomsss........", "...................smbaasoaooooooooosss.....", "...................smmaoboooooooooooobbs....", "...................ssemoooooooooooooooobs...", "..................smaooooooooooooooooooas...", "..................sbooooooooooooooooooooos..", "..................soooooooooooooooooobbbbbs.", ".................sbooooooooossoooooobbbbbbs.", ".................bboooooooosoasooooobbbbbbs.", "...............sbaoooooooooosssooooobbeabas.", "............nssbooooooooooooossooooobbbbbbs.", "..........embabooooooooooooooooooooobbbbbbs.", "........oommaaoooooooooooooooooooooobbbbbbs.", ".......ooeoooooooooooooooooooooooooobbbbbbs.", ".......oaooooooooooooooooooooooooooobbbbbbs.", ".....eaaoooooooooooooooooooooooooooobbbbbbs.", "....ebaooooooooooooooooooaooooooooooobbbms..", "....eoooooooooooooooooooooaaoooaaaaabssss...", "....eoooooooooooooooooooooooaabmmmossa......", "...eooooooooooooooooooooooooaaammmmss.......", "...oooooooooooooooooooooooooooaabasb........", "..eoooooooooooooooooooooooooooaaabbs........", "..ooooooooooooooooooooooooooooaaaabs........", ".sbooooooooooooooooooooooooooooaaaas........", ".sboooooooooooaaoooooooooooooooaaaas........", ".saaoooooooooooaaaooooooooooooaaaaas........", ".saaooooooooooooooaoooooooooooababms........", ".saaaooooooooooooooboaaaoooooabbbeo.........", ".saaaoooooooooooooobaaaaaooobambbss.........", ".saaaaoooooooooooooamaaaaoooeembms..........", ".sbaaaoooooooooooooosabmoooossbbs...........", ".smbaaaaaooooooooooasbmeoooossbbs...........", "..sbbaaaaaaaoaaoooaasbesoooossbbs...........", "..smbbaaaaaaaaoaaaaasbesbaoassbbs...........", "...smbbaaaaaaaaaaamssobmsaabssmmms..........", "...smbbbaaaabaaaabossammsabbesemmss.........", "....ssbbbbbbbbbbbbbbessssemmeesmmss.........", "......sssssssbbbbbbeos...semmosssss.........", ".............sssssssss....sssss............."],
    ["............................................", "............................................", "...................ssss.....ssss............", "..................smeeos.ssssmmms...........", "..................smbeessbbsmbbms...........", "..................seebabooosmbamsss.........", "..................ssboooooommbbsmoms........", "..................sboooooooabbbeooobs.......", ".................sbooooooooooooooooobs......", ".................soooooooooooooooooooms.....", "................smoooooooooooooooooooos.....", "................sboooooooooooooooosoooms....", "...............smoooooooooooooooosssoobs....", "...............saoooooooooooooooosssoobs....", "..............sbaooooooooooooooooossobbs....", ".............seaoooooooooooooooooooooems....", "............smaoooooooooooooooooooooobbs....", "..........soboooooooooooooooooooooooobbs....", "..........baaoooooooooooooooooooooooabbs....", ".........aaooooooooooooooooooooooooabbs.....", "........aooooooooooooooooooooooaaaaabms.....", ".......aaooooooooooooooooooooobbabbmss......", ".......aooooooooooooooooooooooobmeos........", "......mooooooooooooooooooooooooamss.........", "......aooooooooooooooooooooooooobs..........", ".....aooooooooooooooooooooooooooas..........", ".....aooooooooooooooooooooooooooas..........", "...sbaooooooooooooooooooooooooooos..........", "...sbaaoooooooooooooooobaooooooooos.........", "...sbaoooooooooooooooooobbooooooabs.........", "...saaaoooooooooooooooooobaoaooobbs.........", "...saaaaoooooooooooooooooamaaooobms.........", "...sbaaaooooooooooooooooooebbooobos.........", "...sbaaaaooooooooooooooooobsmooobs..........", "...sbbaaaaoooooooooooooooobsoooobs..........", "...smbaaaaaooooooooooooooaassaoobs..........", "....sbbaaaaaooooooooooooaaassaoobs..........", "....sbbbaaaaaaoooooooooaaabssmaabss.........", ".....sbbbaaaaaaooooooaaaaaoesmaamas.........", ".....smbbbbaaaaaaaaaaaaabssssobbeeos........", "......smbbbbbbaaaaaaabbbbbmossoeeoss........", ".......ssmbbbbbbbbbbbbbbbmmss.sssss.........", ".........sssssssmbbbmsssssss................", "................sssss......................."],
    ["..................sss.......................", ".................ssess.....sss..............", "................sbbbbos.sssmmmsss...........", "................sbbbmossabsmbaames..........", "................semmeboooosmbbbbsms.........", "................ssmboooooosebbbboobs........", "...............ssebooooooobembbboooos.......", "...............ssaoooooooooambaaoooasa......", "...............sbooooooooooooooooooobs......", "...............sooooooooooooooooooooos......", "..............sbooooooooooooooooooooomsb....", "..............saoooooooooooooooooooooasb....", "..............saoooooooooooooooooooooasb....", "..............saoooooooooooooooooooooasb....", "..............sboooooooooooooooooooooasa....", ".............sbaaaaoooooooooooooooooaasb....", "...........ssboooooooooooooooooooooaaasb....", "...........maooooooooooooooooooooaaaabsb....", ".........ebaooooooooooooooooooooaaaabes.....", "........eaooooooooooooooooooooooaambes......", "........boooooooooooooooooooooooaambes......", ".......baoooooooooooooooooooooooobems.......", "......eooooooooooooooooooooooooooames.......", "......aooooooooooooooooooooooooooabs........", "......ooooooooooooooooooooooooooooas........", ".....booooooooooooooooooooooooooooas........", ".....aooooooooooooooooooooooooooaoas........", "...sbaooooooooooooooooooooooooooaaas........", "...sboooooooooooooooooooooeboooooaabs.......", "...saaooooooooooooooooooooobmaaabaabs.......", "...saaaooooooooooooooooooooobmabbaaas.......", "...saaooooooooooooooooooooooabmmbaaas.......", "...saaaoooooooooooooooooooooooambaaas.......", "...saaaoooooooooooooooooooooooomeaaas.......", "...saaaaaoooooooooooooooooooooaasaabs.......", "...sbaaaaooooooooooooooooooooaaasbabs.......", "...sebaaaaooooooooooooooooooaaabsbbbs.......", "...eobbaaaaaooooooooooooooaaaabbsebbs.......", "....sbbbaaaaaaaooooooooaaaaaaabasemmms......", "....smbbbaaaaaaaaaaaaaaaaaaaabbsssemms......", ".....sbbbbabaaaaaaaaaaaaaabbbbbmmsomms......", "......sembbbbbbbbbbbbbbbbbbbbbmemssss.......", "........sssmbbbbbbbbbbbbbmsssssss...........", "...........sssssssssssssss.................."],
    ["............................................", "............................................", "............................................", "............................................", "............................................", "............................................", "......................sss.....sss...........", ".....................sbbes...smbes..........", ".....................sbaaesssmbbbs..........", ".....................smabasaooooas..........", ".....................sobooaooooooaon........", "....................sbbeooaoooooooass.......", "...................sboooooooooooooooass.....", "..................saobsmaoooooooooooooe.....", ".................saoasmaeoooooooooooooa.....", "................sbooambesoooooooooooooobn...", "..............ssbooosbbesooooooooooooooos...", "............ssbboooosbbesooooooooooooooobs..", "............aaoooooosbbesoooasooooooooooas..", "..........aaooooooooobbmsooosasoooooobaabbs.", ".........aoooooooooamabesoooossooooobaabbbs.", "........ooooooooooooaobesoooooooooooabbbbbs.", ".......aoooooooooooaoabsaooooooooooobbeamas.", "......aoooooooooooaooaoboooooooooooabababon.", "......ooooooooameaooabsaooooooooooobaaabbs..", ".....oooooooabaaooooaaboooooooooooobbbbbbs..", ".....ooooooaoooooooobsaooooaaoooooobbbbbs...", "....aooooooooooooooomaooooooabaooooobbbeb...", "....oooooooooooooooasboooooooaeabaabmss.....", "...booooooooooooooobsbooooooooabossss.......", "...aooooooooooooooobsaooooooooaabs..........", "...aaoooooooooooooameaoooooooaaabs..........", ".sbaaoooooooooooooasmaoooooooaabbs..........", ".saaaooooooooooooabsbaaaooooaabbe...........", ".saaaaooooooooooaabsaaaaoooobmbbs...........", ".sbaaaoooooooooaababaamboooosbbbs...........", ".sbaaaaoooooaoaaabsbaabsoooosbbbs...........", ".smbaaaaaaaoaaaabebaaabsoooosbbbs...........", "..sbaaaaaaaaaaabmmbaaabsaooosbbms...........", "..smbaaaaaaaaabbmbaaaabsmaoasmmes...........", "...sbbaaaaaaabbobbaabbbesaaasemeo...........", "...smbbaaaabbmebbaabbbmesmbbeseeos..........", "....sobbbbbmebbbbbbbesssssmeosssss..........", "......sssssssssssssss.....ssss.............."],
    ["............................ssss............", "....................ssss..ssmbbes...........", "...................sbbmessmmaaaamsss........", "...................sbbbmssboooooaaao........", "...................sbaaasooooooooooosse.....", "...................seaooboooooooooooobms....", "...................sseooooooooooooooooobs...", "..................smbooooooooooooooooooob...", "..................sbooooooooooooooooooooos..", "..................soooooooooooooooooobbbbbs.", ".................saooooooooossoooooobbbbbbs.", "................bbaoooooooosaasooooobbbbbbs.", "................oaooooooooossssooooobeoabos.", "...............eaoooooooooooassooooobbbbabs.", ".............ssaoooooooooooooooooooobbbbbbs.", ".............aaooooooooooooooooooooobbbbbbs.", "...........oaooooooooooooooooooooooobbbbbbs.", ".......e.aooooooooooooooassmoooooooobbbbbbs.", ".......aaooooooooooooooaomesbooooooobbbbbbs.", "......aooooooooooooooooobbmesaooooooobbbms..", "......ooooooooooooooooembbmmsaooooooomees...", ".....aooooooooooooooooobbbmesaoaabaabesss...", ".....oooooooooooooooabbbbbeesaammmess.......", "....oooooooooooooooabobbbmesaoaabbs.........", "....ooooooooooooaamoabaabmsaooaaabs.........", "...oooooooooaabeeobaooaabesooooaaabs........", "...aooooooaaooooooooooaamsbooooaaaas........", "...ooooooooooooooooooabbesoooooaaaas........", "..aoooooooooooooooooabeesaooooaaaaas........", "..aooooooooooooooooabessaoooooaaaaas........", "sbaoooooooooooooooaabsbaoooooaabaabs........", "saaaoooooooooooooaaamsaaooooobbbaas.........", "sbaaooooooooooooaaabmsaaooooobmbbbs.........", "saaaaoooooooooooaaabsmaaoooooobbmbs.........", "saaaaooooooooooaaaambmmbooooosbbss..........", "sbaaaaooooooooaaaabebbmmooooosbbss..........", "sbbaaaaaaaooaaaaabobbbbmooooosbbss..........", "smbaaaaaaaaaaaaaabobbbbeaoooosbbss..........", ".sbbaaaaaaaaaaaabbmbbbbeaoooosbbss..........", ".smbbaaaaaaaaaabbmbbbbbbbaoaasemss..........", "..sbbbaaaaaaaabbmbbbbbbbsbbbmsoeeos.........", "..sbbbbbaaaabbbmbbbbbbbesmbbbeseoos.........", "...sobbbbbbbbbmmmbbbmssssseeeesssss.........", ".....ssssssssssssssss.....sssss............."],
    ["............................................", "............................ssss............", "....................ssss..ssmbamsn..........", "...................sbbmesbssmabmsn..........", "...................sbbbessbbooooabss........", "...................sbaaasooooooooooosss.....", "...................smbaoaooooooooooooobs....", "...................ssebooooooooooooooooas...", "..................smaooooooooooooooooooas...", "..................saooooooooooooooooooooos..", "..................sooooooooooooooooooobbbbss", ".................saooooooooossooooooobbbbbas", ".................saooooooooasasooooobbbbbaas", "...............osaooooooooossasooooobbeaboss", ".............ssmaoooooooooooossooooobbbbabss", "...........eebaaoooooooooooooooooooobbaaaas.", "..........aooaaooooooooooooooooooooobbbaaas.", "........bobooooooooooooooooooooooooobbbaabs.", "........oaoooooooooooooooooooooooooobbbbbbse", ".......aaooooooooooooooooooooooooooobbbbbbsn", "......aooooooooooooooooooaaooooooooooobbms..", ".....aooooooooooooooooooooaoooooooooobmeoe..", ".....ooooooooooooooooooooooaoooaaaaabbsss...", "....ooooooooooooooooooooooooaabmmmesss......", "....oooooooooooooooooooooasssoaaabsb........", "...aooooooooooooooooooooommmabaaaabs........", "...ooooooooooooooooooooommmmmsoaaabs........", "...ooooooooooaaaooooooooabbeesoaaaas........", "..aooooooooooooabmbaoooabbbmesoaaaas........", "..aoooooooooooooooobboaebbbmmoaaaaas........", "sbaoooooooooooooooooaamobbmsaoaaaabs........", "sbaoooooooooooooooooaeebbbmsaoabaams........", "saaaooooooooooooooooooooabebaaabbas.........", "saaaaooooooooooooooooooobmsooambbms.........", "saaaaooooooooooooooooabbmsaoosbbms..........", "sbaaaaooooooooooooooabmssbooosbbms..........", "sbbaaaaoooooooooooaaabmmaaooosbbms..........", "smbaaaaoaaooooaaaaaababmooooosbbes..........", ".sbbaaaaaaaaaaaaaaabsbbbooooosbbes..........", ".smbbaaaaaaaaaaaaababbbbbaoaasmmes..........", "..smbbaaaaaaaaaabbembbbbababbsemeos.........", "..sbbbaaaaaaaaabbmmbbbbesmbbbeseeos.........", "...sobbbbbbbbbbmmbbbmssssseeeesssss.........", ".....ssssssssssssssss.....sssss............."]
  ];
  function draw(ctx, frame) {
    var map = FRAMES[frame] || FRAMES[0];
    ctx.clearRect(0, 0, 44, 44);
    for (var y = 0; y < map.length; y++) {
      var row = map[y];
      for (var x = 0; x < row.length; x++) {
        var ch = row[x];
        if (ch === '.') continue;
        ctx.fillStyle = COLORS[ch];
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  window.SQMango = { w: 44, h: 44, draw: draw };
})();
