/* ============================================================
   ScoreQuest — Mango, the capybara waiting to be rescued
   ------------------------------------------------------------
   Quantized via quantize_v4.py (area integration, clean interior
   palette, enforced outline) from Magnolia's sprite art. Frames:
   0 sit, 1 turning (side), 2 back turned, 3/4/5 ear-scratch
   (up / mid / low). Canvas 40x40, bottom-aligned.
   Regenerate: python3 quantize_v4.py <img> out.json
     --palette sprites/mango_palette.json --scale 16.4
   ============================================================ */
(function () {
  'use strict';
  var COLORS = {"o": "#dead93", "b": "#000000", "s": "#c38f76", "h": "#a8765f", "m": "#4d342f", "e": "#82594b"};
  var FRAMES = [
    ["........................................", "........................................", "........................................", ".........................bbbb...........", "..................bbbb..behemb..........", ".................beeembbessshmbb........", ".................behhemhsooooshhbbb.....", ".................bmhsshoooooooooseeb....", ".................bbmhooooooooooooosb....", "................behsooooooooooooooosb...", "................bhoooooooooooooooooosb..", "................bsooooooossooooooshhhhb.", "...............bhooooooosmbhooooshhhhhb.", "..............besoooooooebmmooooshemhmb.", "............bbesoooooooooebmoooosheeheb.", "...........bmesoooooooooooooooooshhhhhb.", ".........bbhssooooooooooooooooooshhhhhb.", ".......bbsooooooooooooooooooooooshhhhhb.", "......bsooooooooooooooooooooooooshhhhhb.", ".....bsooooooooooooooooooooooooosshhhmb.", "....bsoooooooooooooooooooooooooooseemb..", "....booooooooooooooooooosooosshhhebbb...", "...bsoooooooooooooooooooossheembbb......", "...boooooooooooooooooooooossshb.........", "..bsooooooooooooooooooooooossseb........", "..boooooooooooooooooooooooossssb........", ".bsoooooooooosoooooooooooooosssb........", ".bsoooooooooossoooooooooooossssb........", ".bssoooooooooosssoooooooooossssb........", ".bsssooooooooooossoosooooosshseb........", ".bsssoooooooooooosssssooosshhhb.........", ".bssssooooooooooosehssoooseeheb.........", ".bhsssoooooooooooomehsooohmhhb..........", ".behsssssoooooooosmeehooohmhhb..........", "..bhhssssssosooossmemeooohmhhb..........", "..bmhhssssssssosshmemmhssemhhb..........", "...behhsssssssssebbbemmssebmemb.........", "....bbhhhhhhhhhhhhebbbbehembmmb.........", "......bbbbbbhhhhhemb...bmmmbbbb.........", "............bbbbbbbb....bbbb............"],
    ["........................................", "........................................", ".................bbbb....bbbb...........", ".................beembbbbmeeb...........", ".................bhemmehmehhmb..........", ".................behssoomeshmeb.........", ".................bhsooooseheessbb.......", "................beooooooossssooseb......", "................boooooooooooooooseb.....", "...............bhoooooooooooooooosb.....", "...............bsoooooooooooooshooeb....", "..............bhoooooooooooooombhohb....", "..............bsoooooooooooooobbhosb....", ".............bhooooooooooooooohbhshb....", "............besooooooooooooooooooheb....", "...........bhsoooooooooooooooooooshb....", ".........bbhoooooooooooooooooooooshb....", "........bhsooooooooooooooooooooosheb....", ".......bssoooooooooooooooooossssshb.....", "......bsooooooooooooooooooosssshmbb.....", "......bsooooooooooooooooooosheebb.......", ".....bhoooooooooooooooooooooseb.........", ".....bsooooooooooooooooooooooeb.........", "....bsooooooooooooooooooooooohb.........", "...besooooooooooooooooooooooohb.........", "...bhsooooooooooooooooooooooohb.........", "...bssooooooooooooooossoooooosmb........", "...bssoooooooooooooooossooooohmb........", "...bssssooooooooooooooohhsooohmb........", "...bssssooooooooooooooohhhooohb.........", "...bhssssoooooooooooooosmmoooeb.........", "...bhhssssooooooooooooosmmsooeb.........", "...bmhsssssooooooooooossmbsooeb.........", "....bhhsssssooooooooosshmbhsseb.........", "....bmhhssssssooooossssemmeshebb........", ".....bhhhhssssssssssssembmmhhmmb........", ".....bmhhhhhhssssssshheembbmemmb........", "......bbmhhhhhhhhhhhhhhebb.bbbbb........", "........bbbbbbbehhebbbbbb...............", "...............bbbb....................."],
    ["........................................", "................bbbb....bbb.............", "...............behemb.bbbmmbbb..........", "...............bhhembbeebehemmb.........", "...............beeeeeessbehshmmb........", "...............bmehsoooobehhhmsmb.......", "..............bbmhoooooomeehheosmb......", "..............bmsoooooooohhssooosb......", "..............bsooooooooooooooooosb.....", "..............booooooooooooooooooob.....", ".............bhooooooooooooooooooohb....", ".............bsooooooooooooooooooosb....", ".............bsooooooooooooooooooosb....", ".............bhooooooooooooooooooosb....", "............bhssssooooooooooooooossb....", "...........bhooooooooooooooooooosssb....", ".........bbsoooooooooooooooooosssshb....", "........bhsoooooooooooooooooosssshb.....", ".......bhoooooooooooooooooooosshhmb.....", "......bhoooooooooooooooooooooshmemb.....", "......bsoooooooooooooooooooooohemb......", ".....bhoooooooooooooooooooooooseb.......", ".....booooooooooooooooooooooooohb.......", "....bhooooooooooooooooooooooooohb.......", "....bsooooooooooooooooooooooosohb.......", "...bhsooooooooooooooooooooooosshb.......", "...bsoooooooooooooooooooehoosssseb......", "...bssooooooooooooooooooosesshsshb......", "...bssoooooooooooooooooooosehesshb......", "...bsssoooooooooooooooooooosmhsshb......", "...bsssoooooooooooooooooooooeesshb......", "...bssssoooooooooooooooooooshbsseb......", "...bhssssooooooooooooooooosshbhseb......", "...behsssoooooooooooooooossshbhheb......", "....bhhssssssoooooooososssshebeheb......", "....behhsssssssosossssssssshmbbeemb.....", ".....bhhhshsssssssssssssshhhhebmmmb.....", "......behhhhhshhshshhhhhhhhemmbbbb......", ".......bbbmhhhhhhhhhhhhebbbbbb..........", "..........bbbbbbbbbbbbbb................"],
    ["........................................", "........................................", "........................................", "........................................", "....................bbb.....bbb.........", "...................bmheb...beeb.........", "...................bmhsebbbehheb........", "...................bmhssbsoooosb........", "...................bmesosoooooosbb......", "..................beshooooooooooohb.....", ".................bhshhoooooooooooosb....", "................bhoemmeoooooooooooosb...", "...............bhosmemmsoooooooooooosb..", ".............bbhooemhemsooooooooooooob..", "...........bbehoooeehebsooooooooooooosb.", ".........bbhhooooomehebsooemoooooooooob.", "........bssoooooooeesebsosbbmooooosssshb", ".......booooooooosehseboooebmoooossssssb", "......boooooooooohhoseboooossoooossheseb", ".....booooooooooheoohmhoooooooooossemhmb", "....booooooooooseooseeooooooooooossssshb", "...bhooooooooseeooohmhooooooooooossssseb", "...booooooosssooooomeoooooooooooosssshb.", "..bhoooooooooooooosmhoooossooooossssseb.", "..boooooooooooooooemsoooooshhssoosheeb..", "..booooooooooooooomeoooooooshemmbmbbb...", ".bsoooooooooooooosmeooooooooshmb.b......", ".bsoooooooooooooohmhoooooooossb.........", "besooooooooooooooemsooooooosssmb........", "bssooooooooooooosmesssoooosshhb.........", "bssoooooooooooossmesssoooosehmb.........", "bssooooooooooossemhshhoooomhsb..........", "bhsossooooooossseesshmoooomhsb..........", "bessossooooossshmhsshmoooobhsb..........", ".bhssosssssssshehssshmsooobhsb..........", ".bessssssssssheehssshbhsosbehb..........", "..bhhsssssssheehssshhmmsssbmemb.........", "..bmehssssheeehsshheembehhmbmmb.........", "...bbeeeeemmeeeeeembbbbbemmbbbb.........", ".....bbbbbbbbbbbbbb.....bbbb............"],
    [".........................bbbb...........", "..................bbbb..behhmb..........", ".................beeembbessshebb........", ".................behhemhsooooohhbbb.....", ".................behsshoooooooooseb.....", ".................bbmsooooooooooooohb....", ".................bmeooooooooooooooohb...", "................besooooooooooooooooosb..", "................bsoooooooooooooooossshb.", "...............beooooooooemsooooosssssb.", "...............bsooooooohbbmooooshheseb.", "..............bsoooooooosmbbooooshemhmb.", ".............bhooooooooooseeoooossssshb.", "...........bbeoooooooooooooooooossssssb.", "..........bhsooooooooooooooooooossssssb.", ".......bbbsooooooooooohmhooooooossssssb.", "......bhsooooooooooooemmmhoooooossssshb.", ".....bhooooooooooooohmeemmsooooooshheb..", ".....booooooooooooooeeheebsoooooohemmb..", "....bsooooooooooooosmhhhebsohhhheebbb...", "....booooooooooooooeehhemmsshembbb......", "...boooooooooooooshmhhhebhosshb.........", "...booooooooossheemhsshmeoossshb........", "..boooooooossshhsoooshemsooosssb........", "..boooooooooooooooooshmeoooosssb........", ".bhooooooooooooooossemmsooossssb........", ".bsoooooooooooooossebmsoooossssb........", "besooooooooooooosshmesoooosshshb........", "bssooooooooooooosshmhoooooshhseb........", "bsssooooooooooosssmmhoooooehhhb.........", "bssssoooooooooosshmmhsoooomhheb.........", "bssssooooooooosssmehhsooosbhhb..........", "bhssssoooooosssshmhhesoooobshb..........", "behssssssossssssehhheeoooobssb..........", ".bhhssssssssssshehhhhmooosbshb..........", ".bhhsssssssssshehhhhhmssosbehb..........", "..bhhsssssssshhhhhhhheehshbmemb.........", "..bmehhssssshhhhhhhemmmehhmbmmb.........", "...bbmmmmmmmmmmmmmmbbbbbmmmbbbb.........", ".....bbbbbbbbbbbbbb.....bbbb............"],
    ["........................................", ".........................bbbb...........", "..................bbbb..behhmb..........", ".................beeembbessshebb........", ".................bhshemhsoooooeebb......", ".................behsshoooooooooheb.....", ".................bbmsooooooooooooosb....", "................bmesooooooooooooooosb...", "................bhoooooooooooooooooosb..", "................booooooooooooooooossshb.", "...............beooooooooeesooooosssssb.", "...............bsooooooohbbmooooohheseb.", "..............bsoooooooosmbbooooohemsmb.", "............bbsooooooooooshhooooosssssb.", "..........bbssooooooooooooooooooosssssb.", "........bbosooooooooooooooooooooosssssb.", ".......bsoooooooooooooooooooooooosssssb.", "......bsooooooooooooooooooooooooosssshb.", ".....bsooooooooooooooooooooooooooshheb..", "....bsooooooooooooooooooooooooooohmmb...", "....booooooooooooooooooosooshhhembbbb...", "...booooooooooooooooooooossshhmbb.......", "...booooooooooooooooooommmosshb.........", "..booooooooooooooooooomeemmssshb........", "..boooooooooosoooooooemhemmosssb........", ".bhooooooooooossssooomhhemmosssb........", ".bsoooooooooooooshsosmhhemhosssb........", "besooooooooooooooohheeshmeossssb........", "bssoooooooooooooooohhssemhoshseb........", "bsssoooooooooooooooooshmesshhhb.........", "bsssooooooooooooooooosemsseeheb.........", "bssssooooooooooooooshemeohmhhb..........", "bhssssooooooooooooshmbeoosmhhb..........", "bhhssssooooooooosshmehooosmhhb..........", ".bhhsssssssoosssshbhheooosmhhb..........", ".bhhsssssssssssssmehhmsoohmehb..........", "..bhhsssssssssssemhhhmessebmemb.........", "..bmehssssssshheehhemmmehembmmb.........", "...bbmmmmmmmemmmeembbbbmemmbbbb.........", ".....bbbbbbbbbbbbbb....bbbbb............"]
  ];
  function draw(ctx, frame) {
    var map = FRAMES[frame] || FRAMES[0];
    ctx.clearRect(0, 0, 40, 40);
    for (var y = 0; y < map.length; y++) {
      var row = map[y];
      for (var x = 0; x < row.length; x++) {
        var ch = row[x];
        if (ch === '.') continue;
        ctx.fillStyle = COLORS[ch];
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  window.SQMango = { w: 40, h: 40, draw: draw };
})();
