/* ============================================================
   ScoreQuest — Mango, the capybara waiting to be rescued
   ------------------------------------------------------------
   Quantized from Magnolia's sprite art on Mango's own soft-pink
   palette. Frames: 0 sit, 1 turning (side), 2 back turned,
   3/4/5 ear-scratch (up / mid / low). Canvas 32x32.
   ============================================================ */
(function () {
  'use strict';
  var COLORS = {"a": "#77564e", "b": "#c28f76", "e": "#3b2416", "m": "#77564e", "n": "#727372", "o": "#deac92", "s": "#090500"};
  var FRAMES = [
    ["................................", "................................", "................................", "....................sss.........", "...............ssm.smaos........", "..............ssasssooomss......", "..............smbboooooooose....", "..............ssmooooooooooob...", ".............smbooooooooooooom..", ".............soooooooooooooaass.", "............ssoooooossooooaaaas.", "...........ssooooooossooooaoeas.", ".........nssoooooooooeooooaaaas.", ".........sboooooooooooooooaaaas.", "........ooooooooooooooooooaaaas.", "......boooooooooooooooooooaaass.", "....nooooooooooooooooooooooaao..", "....booooooooooooooboobbbbsssm..", "....oooooooooooooooobbmmoss.....", "....ooooooooooooooooobbaso......", "...ooooooooooooooooooobbss......", ".sbooooooooooooooooooobbbs......", ".sbooooooooboooooooooobbbs......", ".sbbooooooooobooooooobbbss......", ".sbbooooooooooboboooobmas.......", ".sbbbooooooooobabbooomams.......", ".sabboooooooooosaoooomas........", ".smabbbooooooobsmooooaas........", "..ssabbbbbbbbbbsoabobaas........", "...ssabbbbbbbmssasbbaomos.......", "....ssaasssaassossmsssoos.......", ".....ssss.ssss.e..s..esss......."],
    ["................................", "................................", "................................", "..............em.s.sseme........", "..............ssmssssaas........", "..............soaboosbbsms......", "..............soooooobaooos.....", ".............ssoooooooooooss....", ".............mooooooooooooobs...", "............mbooooooooooosoom...", "............ooooooooooooosoos...", "...........sboooooooooooosoas...", "..........smoooooooooooooooos...", "........nsbooooooooooooooooas...", "........bboooooooooooooooobam...", ".......bbooooooooooooooooobss...", "......boooooooooooooooabbsss....", ".....mbooooooooooooooooaoe......", ".....boooooooooooooooooos.......", ".....ooooooooooooooooooos.......", "...ssooooooooooooooooooos.......", "...sabooooooooooooboooooos......", "...sbboooooooooooobbooooas......", "...sbbboooooooooooomboooms......", "...sbbboooooooooooomaoooes......", "...sabbbooooooooooobsooos.......", "...smbbbboooooooooobsboos.......", "....ssabbboooooooobasabbs.......", ".....ssbbbbboooobbbomsbbes......", "......saabbbbbbbbbaeesmooe......", "......smaaasssaaaaaossssss......", ".......sssss.ssmsssss..........."],
    ["................................", "................................", "................................", "..............sme...ss..........", ".............ssmmsbmmbm.s.......", ".............smmaoobmasss.......", "............nsmooooomaaeo.......", "............saoooooobabooos.....", "............soooooooooooooos....", "...........ssoooooooooooooos....", "...........sboooooooooooooob....", "...........sboooooooooooooob....", "...........mbbbooooooooooobb....", "..........soooooooooooooobbb....", "........bmoooooooooooooobbbs....", "........boooooooooooooobbams....", ".......booooooooooooooooamm.....", ".......ooooooooooooooooobms.....", "......ooooooooooooooooooos......", ".....sooooooooooooooooooos......", ".....sooooooooooooooooobbs......", "....sbooooooooooooobaooobss.....", "....sbboooooooooooooambabbs.....", "....sbooooooooooooooobmmbbs.....", "....sbbooooooooooooooobmbbs.....", "....sbbboooooooooooooobsbas.....", "....ssbbooooooooooooobbsaas.....", ".....msbbbobooooooobbbasmas.....", "......sabbbbbobbbbbbbbassmms....", ".....sssaabbbbbbbbbaaaamsss.....", ".......ssmaaaaaaaaamssss........", ".........sssssssssss............"],
    ["................................", "................................", "................................", "................................", "................ns...smes.......", "................sbbssmbbs.......", "................obbsoooobs......", "...............ssmoboooooss.....", "..............sbooooooooooobs...", ".............sobembooooooooob...", "............sooeammoooooooooos..", "..........sssoosamsooooooooooos.", "........embbooosamsoomoooooooos.", ".......bbooooooebmsooesooooobbss", "......boooooooeabmsoossoooobbbbs", ".....booooooooboasoooooooooboaes", "....booooooooboooaoooooooobbbbas", "...soooooobmooobsooooooooobbbbss", "...ooooobboooooaaoooboooooabbbs.", "..eoooooooooooomoooooabooobbsms.", "..eooooooooooobsooooobaebbsms...", "..boooooooooooasoooooobbs.......", "..boooooooooobmmoooooobbs.......", "sbboooooooooobsbbooooobss.......", "sboooooooooobasbbbooobss........", "sbboooooooobboabaaooosb.........", "ssbbooooboobbsabbsooosbe........", ".sabobbobbbbabbbbsooosbs........", ".smbbbbbbbbambbbbsbobsas........", "..ssbbbbbbaobbbaaoaaasoos.......", "...ssaaaaoabbbssssemmoses.......", "....sssssssssss....ssss........."],
    ["................................", "....................sss.........", "...............ss..smbms........", "..............ssssssooobss......", "..............sabbooooooooos....", "..............ssoooooooooooob...", ".............ssbooooooooooooo...", ".............sooooooooooooobbbs.", "............sboooooossooooaabbs.", "............soooooooseoooobmeos.", "...........sooooooooosoooobbbbs.", "..........sooooooooooooooobbbbs.", "........mboooooooooooooooobbbbs.", ".......booooooooobsmooooooabbbs.", "......boooooooooosmesoooooaaass.", "....nooooooooooooaamsbobbbsssm..", "....ooooooooooooaaamsbamoss.....", "....oooooooooobaaaaebobaso......", "....oooooooobmoebbmsoobbss......", "...ooooooboooooobaeooobbbs......", "...oooooooooooooamsooobbbs......", "..booooooooooobbsboooobbbs......", ".sboooooooooobbaboooobabss......", ".bbbooooooooobbsbooooaabs.......", ".bbboooooooobbasboooooass.......", ".bbbooooooobbbsaaoooosas........", ".sbbbboboobbbboaaoooosbs........", ".sabbbbbbbbbbmaaamooosbs........", ".ssabbbbbbbaaaaaaebobsms........", "..ssabbbbbaaaaaaamaaasmms.......", "...ssaaaaaamaaamsssmoosss.......", "....ssssssssssss...sss.........."],
    [".....................sss........", "...............sss..sbbms.......", "..............ssaosssooobss.....", "..............sabbsooooooooss...", "..............ssmooooooooooobs..", ".............ssbooooooooooooobs.", ".............sbooooooooooooooob.", ".............moooooooooooooobbbs", "............nboooooobesoooobbbbs", "............moooooooossooooboebe", "..........seooooooooooooooobbbbs", "..........boooooooooooooooobbbbs", ".....nsoooooooooooooooooooobbbbs", ".....sooooooooooooooooooooobbbbs", ".....booooooooooooobooooooooaame", "....boooooooooooooooboobbbbssss.", "...ooooooooooooooooooobmmoss....", "...oooooooooooooooossobbaso.....", "..boooooooooooooooemosbbbss.....", "..oooooooobbooooooeammobbbs.....", "..oooooooooobaboooaamsobbbs.....", "..oooooooooooobmoobambbbbbs.....", "sbbooooooooooooboabmsobabms.....", "sbbbooooooooooooooambbbabs......", "sbbboooooooooooobammomaas.......", "sabbboooooooooobassoosaas.......", "ssbbbbobooooobbaeaooosaas.......", ".sabbbbbbbbbbbasaaooosaas.......", ".ssabbbbbbbbbaeaaaabbsmms.......", "..saabbbbbbaaoaaaasaamsmms......", "..sesaaaaaaamaamsssmmmssss......", "....ssssssssssss...ssss........."]
  ];
  function draw(ctx, frame) {
    var map = FRAMES[frame] || FRAMES[0];
    ctx.clearRect(0, 0, 32, 32);
    for (var y = 0; y < map.length; y++) {
      var row = map[y];
      for (var x = 0; x < row.length; x++) {
        var ch = row[x];
        if (ch === '.') continue;
        ctx.fillStyle = COLORS[ch];
        ctx.fillRect(x, y, 1, 1);
      }
    }
  }
  window.SQMango = { w: 32, h: 32, draw: draw };
})();
